FROM php:8.3-apache
ARG IMAGICK_PHP83_FIX_COMMIT=9df92616f577e38625b96b7b903582a46c064739

RUN apt-get -q update \
    && apt-get -yq upgrade \
    && export PHP_DEV_DEPS='libmagickwand-dev unzip' \
    && apt-get -yq install --no-install-recommends libmagickwand-6.q16-6 $PHP_DEV_DEPS \
    && curl -L https://github.com/remicollet/imagick/archive/${IMAGICK_PHP83_FIX_COMMIT}.zip -o /tmp/imagick-issue-php83.zip \
    && unzip /tmp/imagick-issue-php83.zip -d /tmp \
    && pecl install /tmp/imagick-${IMAGICK_PHP83_FIX_COMMIT}/package.xml \
    && docker-php-ext-enable imagick \
    && apt-get purge -y $PHP_DEV_DEPS $PHPIZE_DEPS \
    && apt-get autoremove -y --purge \
    && apt-get clean all \
    && rm -rf /var/lib/apt/lists/* /tmp/*

RUN apt-get update && apt-get install -y \
    libzip-dev libexif-dev libpng-dev libjpeg-dev libicu-dev imagemagick $PHPIZE_DEPS \
    && docker-php-ext-configure gd --with-jpeg \
    && docker-php-ext-install mysqli zip exif gd intl \
    && a2enmod rewrite \
    && a2enmod ssl \
    && apt-get purge -y $PHPIZE_DEPS \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/*